config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :events, except: [:edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  def index
    @events = Event.all
  end

  def show
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.create(event_params)
    if @event.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @event.delete
    redirect_to root_path
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:start_at, :end_at, :doctor, :address, :praxis, :website)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @currentdate = Date.today
    @first_dates = set_multiple_months(@currentdate)
    @months_with_dates = get_dates_and_amounts(@first_dates)
    @events = Event.all
  end

  private

  def get_dates_and_amounts(firsts)
    all_dates = []
    firsts.each do |first|
      month = {}
      month[:first_date] = first
      amount = amount_of_days(first)
      month[:num] = amount
      date_array = set_dates_of_month(amount, first)
      month[:dates] = date_array
      all_dates << month
    end
    all_dates
  end

  def set_multiple_months(start_date)
    next_month = start_date.at_beginning_of_month
    first_dates = []
    counter = 1
    while counter <= 5
      first_dates << next_month
      next_month = next_month.next_month
      counter += 1
    end
    first_dates
  end

  def amount_of_days(date)
    Time.days_in_month(date.month, date.year)
  end

  def set_dates_of_month(number, day)
    counter = 1
    dates = []
    while counter <= number
      date = Date.new(day.year, day.month, counter)
      dates << date
      counter += 1
    end
    dates
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/index.html.erb
<div class="container bg-dark my-4 py-5">
<h1 class="text-white pb-3 text-center">Alle Gespräche</h1>
<%= link_to 'Kalendar', root_path, class:'links' %>

<% @events.each do |event| %>
<ul class="list-group text-center w-50 m-auto">
  <li class="list-group-item"><strong>Termin: </strong>
    (<%= link_to 'Löschen', event, method: :delete, data: { confirm: 'Are you sure?' } %>)
  </li>
  <li class="list-group-item">Praxis: <strong><%= event.praxis %></strong></li>
  <li class="list-group-item">Doktor: <strong><%= event.doctor %></strong></li>
  <li class="list-group-item">Adresse: <strong><%= event.address %></strong></li>
  <li class="list-group-item">Website: <strong><%= event.website %></strong></li>
  <li class="list-group-item">Uhrzeit: <strong><%= event.start_at %> - <%= event.end_at %></strong></li>
</ul>
<% end %>
</div>

app/views/events/new.html.erb
<div class="container bg-dark my-4">
  <h1 class="text-center py-4 text-white">Füge einen Termin hinzu</h1>
  <div class="form">
    <%= simple_form_for(@event) do |f| %>
      <%= f.input :doctor %>
      <%= f.input :praxis %>
      <%= f.input :start_at %>
      <%= f.input :end_at %>
      <%= f.input :address %>
      <%= f.input :website %>
      <div class="text-center">
        <%= f.submit "Submit", class:"btn submit-button mb-5" %>
    <% end  %>
  </div>
    </div>
</div>

app/views/events/show.html.erb
<div class="container bg-dark my-4 py-5">
<h1 class="text-white pb-3 text-center"><%= @event.praxis %></h1>
<%= link_to 'Kalendar', root_path, class:'links' %>

<ul class="list-group text-center w-50 m-auto">
  <li class="list-group-item">Praxis: <strong><%= @event.praxis %></strong></li>
  <li class="list-group-item">Doktor: <strong><%= @event.doctor %></strong></li>
  <li class="list-group-item">Adresse: <strong><%= @event.address %></strong></li>
  <li class="list-group-item">Website: <strong><%= @event.website %></strong></li>
  <li class="list-group-item">Uhrzeit: <strong><%= @event.start_at %> - <%= @event.end_at %></strong></li>
</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Victor</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container bg-dark my-5 pb-5">
  <h1 class="text-center pt-5 text-white">Victors Kalendar</h1>
  <%= link_to 'Neuer Termin', new_event_path, class:'links' %>
  <%= link_to 'Alle Termine', events_path, class:'links pl-2' %>
  <div id="carouselExampleControls" class="carousel slide" data-interval="false" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <h1 class="text-center text-white">Klick für Juli 2019</h1>
      </div>
      <% @months_with_dates.each do |month_with_dates| %>
        <div class="carousel-item">
          <div class="jzdbox1 jzdbasf jzdcal">
            <div class="jzdcalt pt-3"><%= month_with_dates[:first_date].strftime("%B %Y") %></div>
              <div class="jzdcalt week">
                <span>Mo</span>
                <span>Di</span>
                <span>Mi</span>
                <span>Do</span>
                <span>Fr</span>
                <span>Sa</span>
                <span>So</span>
            <% num_first = month_with_dates[:first_date].wday - 1 %>
            <% num_first = num_first + 7 if num_first == -1 %>
            <% num_first.times do |i|  %>
              <span class="jzdb"></span>
            <% end %>

            <% month_with_dates[:dates].each do |date| %>
              <% @current_events = @events.select { |event| event[:start_at].to_date == date } %>
              <% if @current_events.any? %>
                <span class="circle" data-title=<%= @current_events.first.doctor %>><%= link_to date.day, event_path(@current_events.first), class:'link-calendar' %></span>
              <% else %>
                <span><%= date.day %></span>
              <% end %>
            <% end %>

            <% num_last = month_with_dates[:first_date].end_of_month.wday - 7 %>
            <% num_last = - num_last %>
            <% if num_last != 7 %>
              <% num_last.times do |i| %>
                <span class="jzdb"></span>
              <% end  %>
            <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer py-4 w-100">
  <p class="text-center">Created by Jette Bakemeier</p>
</footer>